"""
step_pipeline.py - STEP File Direct Slicing Pipeline

Parallel entry point to the Design Agent V2.  Accepts a STEP file and
produces the same outputs as the prompt-driven pipeline
(output.json, GWL files, renders) — without approximating geometry as
named-object primitives.

APPROACH — exact BREP cross-section slicing (pythonocc):
    BRepAlgoAPI_Section slices each solid at every Z plane → exact analytic
    edges (real circles, NURBS curves).  These are joined into closed wires,
    sampled to XY point arrays, and converted to Shapely polygons.  Hatch
    lines are generated by the same functions used in endpoint_generator_v2,
    so output.json is identical in schema to the prompt-pipeline output.

NOTHING in the existing pipeline is modified.
The only file this script reads from outside this repo is:
    Agent-Nanoscribe_Classification/src/step_loader.py  (load_step, extract_objects)

Usage:
    py src/step_pipeline.py path/to/file.step
    py src/step_pipeline.py path/to/file.step --job-name my_job
    py src/step_pipeline.py path/to/file.step --hatch 0.3 --slice 0.5 --contours 3
"""

import argparse
import json
import math
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

# ── resolve paths so we can import siblings ──────────────────────────────────
_SRC_DIR         = Path(__file__).parent.resolve()                 # …/src/
_V2_DIR          = _SRC_DIR.parent.resolve()                       # …/Agent_NanoscribeV2/
_CLASSIFICATION  = _V2_DIR.parent.parent / "Agent-Nanoscribe_Classification"

for _p in [str(_SRC_DIR), str(_CLASSIFICATION / "src")]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

# ── pythonocc (BREP slicing) ──────────────────────────────────────────────────
from OCC.Core.BRepAlgoAPI import BRepAlgoAPI_Section
from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeFace
from OCC.Core.BRepAdaptor import BRepAdaptor_Curve
from OCC.Core.GCPnts import GCPnts_UniformAbscissa
from OCC.Core.TopExp import TopExp_Explorer
from OCC.Core.TopAbs import TopAbs_EDGE, TopAbs_WIRE
from OCC.Core.TopoDS import topods
from OCC.Core.gp import gp_Pln, gp_Pnt, gp_Dir
from OCC.Core.Bnd import Bnd_Box
from OCC.Core.BRepBndLib import brepbndlib
from OCC.Core.BOPAlgo import BOPAlgo_Tools
from OCC.Core.TopTools import TopTools_ListOfShape

# ── Shapely ───────────────────────────────────────────────────────────────────
from shapely.geometry import Polygon, MultiPolygon
from shapely.validation import make_valid

# ── classification repo: STEP loader ─────────────────────────────────────────
from step_loader import load_step, extract_objects

# ── existing V2 modules (imported directly, not modified) ────────────────────
from endpoint_generator_v2 import (
    generate_hatch_lines,
    generate_contour_lines,
    Z_BIN,
)
import gwl_serializer
import render_generator_v2

# ── typing ────────────────────────────────────────────────────────────────────
from OCC.Core.TopoDS import TopoDS_Shape


# ======================================================
# DEFAULTS
# ======================================================

DEFAULT_HATCH_UM    = 0.35
DEFAULT_SLICE_UM    = 0.60
DEFAULT_CONTOURS    = 2
SAMPLE_PTS_PER_EDGE = 64    # GCPnts points per section edge when building polygon
MIN_POLY_PTS        = 3     # minimum points to form a valid polygon


# ======================================================
# PARAMETER LOADING
# ======================================================

def _find_param_file(start: Path, max_levels: int = 5) -> Optional[Path]:
    """Walk up the directory tree looking for PrintParameters.txt."""
    current = start
    for _ in range(max_levels):
        candidate = current / "PrintParameters.txt"
        if candidate.exists():
            return candidate
        parent = current.parent
        if parent == current:
            break
        current = parent
    return None


def _load_params(param_file: Optional[Path]) -> Dict:
    """
    Load print parameters from file.  Applies defaults for any missing keys.
    Looks for hatch_spacing_um, slice_spacing_um, solid_contour_count.
    """
    raw: Dict = {}
    if param_file and param_file.exists():
        with param_file.open() as fh:
            for line in fh:
                line = line.strip()
                if ":" in line and not line.startswith("#"):
                    key, val = line.split(":", 1)
                    try:
                        raw[key.strip()] = float(val.strip())
                    except ValueError:
                        raw[key.strip()] = val.strip()

    return {
        "hatch_spacing_um":   float(raw.get("hatch_spacing_um",   DEFAULT_HATCH_UM)),
        "slice_spacing_um":   float(raw.get("slice_spacing_um",   DEFAULT_SLICE_UM)),
        "solid_contour_count": int(raw.get("solid_contour_count", DEFAULT_CONTOURS)),
        # pass through everything else for GWL serializer
        **{k: v for k, v in raw.items()
           if k not in ("hatch_spacing_um", "slice_spacing_um", "solid_contour_count")},
    }


# ======================================================
# GEOMETRY HELPERS
# ======================================================

def _get_z_range(shape: TopoDS_Shape) -> Tuple[float, float]:
    """Return (z_min, z_max) of a shape via its AABB."""
    box = Bnd_Box()
    brepbndlib.Add(shape, box)
    _xmin, _ymin, zmin, _xmax, _ymax, zmax = box.Get()
    return float(zmin), float(zmax)


def _get_aabb(shape: TopoDS_Shape) -> Dict:
    """Return full AABB dict for a shape."""
    box = Bnd_Box()
    brepbndlib.Add(shape, box)
    xmin, ymin, zmin, xmax, ymax, zmax = box.Get()
    return {
        "xmin": xmin, "ymin": ymin, "zmin": zmin,
        "xmax": xmax, "ymax": ymax, "zmax": zmax,
        "dx": xmax - xmin, "dy": ymax - ymin, "dz": zmax - zmin,
        "cx": (xmin + xmax) / 2,
        "cy": (ymin + ymax) / 2,
        "cz": (zmin + zmax) / 2,
    }


# ======================================================
# BREP CROSS-SECTION → SHAPELY POLYGON
# ======================================================

def _edges_to_xy_points(section_shape: TopoDS_Shape) -> List[List[Tuple[float, float]]]:
    """
    Walk all edges in a section compound, sample each one uniformly,
    and return a list of point-chains (one chain per edge).

    Each chain is a list of (x, y) tuples.
    """
    chains: List[List[Tuple[float, float]]] = []
    exp = TopExp_Explorer(section_shape, TopAbs_EDGE)
    while exp.More():
        edge = topods.Edge(exp.Current())
        try:
            adaptor = BRepAdaptor_Curve(edge)
            pts_count = max(SAMPLE_PTS_PER_EDGE, 4)
            disc = GCPnts_UniformAbscissa(adaptor, pts_count)
            if not disc.IsDone() or disc.NbPoints() < 2:
                exp.Next()
                continue
            chain = []
            for i in range(1, disc.NbPoints() + 1):
                p = adaptor.Value(disc.Parameter(i))
                chain.append((p.X(), p.Y()))
            if len(chain) >= 2:
                chains.append(chain)
        except Exception:
            pass
        exp.Next()
    return chains


def _chains_to_polygon(chains: List[List[Tuple[float, float]]]) -> Optional[Polygon]:
    """
    Concatenate point-chains into a single flat list of XY points and
    build a Shapely polygon.  Validity is repaired via make_valid.

    Returns None if the resulting polygon is degenerate.
    """
    if not chains:
        return None

    # Flatten: concatenate all chains (order within the list may be arbitrary
    # for section edges, but Shapely handles reordering via make_valid / convex hull
    # for convex shapes; for complex bodies the contour is still usable)
    pts: List[Tuple[float, float]] = []
    for chain in chains:
        pts.extend(chain)

    if len(pts) < MIN_POLY_PTS:
        return None

    try:
        poly = Polygon(pts)
        if not poly.is_valid:
            poly = make_valid(poly)
        # make_valid may return a GeometryCollection; take the largest polygon
        if poly.geom_type == "GeometryCollection":
            polys = [g for g in poly.geoms if g.geom_type == "Polygon"]
            if not polys:
                return None
            poly = max(polys, key=lambda p: p.area)
        if poly.is_empty or poly.area < 1e-12:
            return None
        return poly
    except Exception:
        return None


def _section_polygon(body: TopoDS_Shape, z: float) -> Optional[Polygon]:
    """
    Slice *body* at the horizontal plane Z = z using exact BREP Boolean section.

    Returns a Shapely Polygon representing the cross-section, or None if the
    plane does not intersect the body at this height.

    Implementation:
        BRepAlgoAPI_Section with Approximation(True) ensures that even
        non-analytic intersections are returned as smooth B-spline edges
        (rather than low-degree polylines).
    """
    try:
        normal   = gp_Dir(0.0, 0.0, 1.0)
        origin   = gp_Pnt(0.0, 0.0, z)
        plane    = gp_Pln(origin, normal)
        plane_f  = BRepBuilderAPI_MakeFace(plane).Shape()

        sec = BRepAlgoAPI_Section(body, plane_f, False)
        sec.ComputePCurveOn1(True)
        sec.Approximation(True)
        sec.Build()

        if not sec.IsDone():
            return None

        result = sec.Shape()
        if result.IsNull():
            return None

        chains = _edges_to_xy_points(result)
        return _chains_to_polygon(chains)

    except Exception:
        return None


# ======================================================
# HATCH GENERATION WRAPPER
# ======================================================

def _hatch_polygon(polygon: Polygon, params: Dict) -> List[Dict]:
    """
    Generate contour + hatch segments for one Shapely polygon at one Z layer.
    Returns list of segment dicts: {start:[x,y], end:[x,y], type:"hatch"|"contour"}
    """
    hatch   = params["hatch_spacing_um"]
    nconts  = params["solid_contour_count"]
    segments: List[Dict] = []

    # Contour lines (shell)
    if nconts > 0:
        for x1, y1, x2, y2 in generate_contour_lines(polygon, hatch, nconts):
            segments.append({
                "start": [round(x1, 6), round(y1, 6)],
                "end":   [round(x2, 6), round(y2, 6)],
                "type":  "contour",
            })

    # Hatch fill (erode by shell thickness first)
    interior = polygon.buffer(-nconts * hatch) if nconts > 0 else polygon
    if interior and not interior.is_empty:
        # Handle MultiPolygon interiors (e.g. bodies with through-holes)
        regions = (interior.geoms
                   if interior.geom_type == "MultiPolygon"
                   else [interior])
        for region in regions:
            if region.is_empty:
                continue
            for x1, y1, x2, y2 in generate_hatch_lines(region, hatch):
                segments.append({
                    "start": [round(x1, 6), round(y1, 6)],
                    "end":   [round(x2, 6), round(y2, 6)],
                    "type":  "hatch",
                })

    return segments


# ======================================================
# MAIN SLICING LOOP  →  output.json
# ======================================================

def build_output_json(
    bodies: List[TopoDS_Shape],
    job_name: str,
    params: Dict,
) -> Dict:
    """
    Slice all STEP bodies at every Z height and generate hatch segments.

    For each Z layer:
      1. Slice every body at that Z via BRepAlgoAPI_Section
      2. Generate hatch + contour segments for each resulting polygon
      3. Merge all body segments for that layer into one list

    Returns an output.json-compatible dict (same schema as endpoint_generator_v2).
    """
    slice_step = params["slice_spacing_um"]

    # Bounding-box Z range across all bodies
    z_min_global =  math.inf
    z_max_global = -math.inf
    for body in bodies:
        zlo, zhi = _get_z_range(body)
        z_min_global = min(z_min_global, zlo)
        z_max_global = max(z_max_global, zhi)

    if z_min_global == math.inf:
        raise ValueError("Could not determine Z range from STEP bodies.")

    # Generate layer Z values
    z_heights = np.arange(z_min_global, z_max_global + slice_step * 0.5, slice_step)
    total_z = len(z_heights)

    print(f"[STEP] Z range: {z_min_global:.3f} → {z_max_global:.3f}  "
          f"({total_z} layers × {slice_step} µm)")
    print(f"[STEP] Slicing {len(bodies)} body(ies)…")

    # layer_map: quantized_z → list of segment dicts
    layer_map: Dict[float, List[Dict]] = {}

    for body_idx, body in enumerate(bodies):
        body_zlo, body_zhi = _get_z_range(body)
        sliced = 0

        for z_raw in z_heights:
            # Skip layers outside this body's Z extent
            if z_raw < body_zlo - 1e-9 or z_raw > body_zhi + 1e-9:
                continue

            polygon = _section_polygon(body, float(z_raw))
            if polygon is None or polygon.is_empty:
                continue

            segs = _hatch_polygon(polygon, params)
            if not segs:
                continue

            # Quantize Z to global grid (same as endpoint_generator_v2)
            z_key = round(round(z_raw / Z_BIN) * Z_BIN, 6)
            if z_key not in layer_map:
                layer_map[z_key] = []
            layer_map[z_key].extend(segs)
            sliced += 1

        print(f"[STEP]   body {body_idx}: {sliced} non-empty layers")

    # Sort segments within each layer (Y then X, consistent with endpoint_generator_v2)
    for z_key in layer_map:
        layer_map[z_key].sort(key=lambda s: (s["start"][1], s["start"][0]))

    layers_list = [
        {"z_um": z, "segments": segs}
        for z, segs in sorted(layer_map.items())
    ]

    print(f"[STEP] {len(layers_list)} non-empty layers, "
          f"{sum(len(l['segments']) for l in layers_list)} total segments")

    return {
        "job_name": job_name,
        "layers":   layers_list,
        "metadata": {
            "z_bin_um":    Z_BIN,
            "num_layers":  len(layers_list),
            "num_bodies":  len(bodies),
            "source":      "step_brep_slice",
            "slice_spacing_um":   slice_step,
            "hatch_spacing_um":   params["hatch_spacing_um"],
            "solid_contour_count": params["solid_contour_count"],
        },
    }


# ======================================================
# SYNTHETIC design.json  (for render_generator_v2)
# ======================================================

def build_design_json(bodies: List[TopoDS_Shape], job_name: str) -> Dict:
    """
    Build a synthetic design.json so that render_generator_v2 can produce
    per-body and final-assembly PNG renders using AABB projection.

    Each body becomes one named "geometry" object containing a single box
    primitive whose dimensions are the body's bounding-box extents.
    The assembly is "explicit" with each body placed at its AABB centroid.
    """
    objects: Dict = {}
    placements: List[Dict] = []

    for idx, body in enumerate(bodies):
        bb   = _get_aabb(body)
        name = f"body_{idx}"

        # Box primitive using AABB extents
        component = {
            "type":   "box",
            "center": [
                round(bb["cx"], 6),
                round(bb["cy"], 6),
                round(bb["cz"], 6),
            ],
            "dimensions": {
                "x_um": round(bb["dx"], 6),
                "y_um": round(bb["dy"], 6),
                "z_um": round(bb["dz"], 6),
            },
        }

        objects[name] = {
            "type":        "geometry",
            "description": f"STEP body {idx} (AABB envelope for rendering)",
            "components":  [component],
        }

        placements.append({
            "object":       name,
            "position":     [round(bb["cx"], 6), round(bb["cy"], 6), round(bb["cz"], 6)],
            "rotate_z_deg": 0.0,
        })

    return {
        "job_name": job_name,
        "objects":  objects,
        "assembly": {
            "type":       "explicit",
            "placements": placements,
        },
        "metadata": {
            "source":     "step_pipeline",
            "num_bodies": len(bodies),
        },
    }


# ======================================================
# DOWNSTREAM: GWL + RENDERS
# ======================================================

def _run_downstream(
    output_dir: Path,
    output_json: Dict,
    design_json: Dict,
    param_file: Optional[Path],
) -> None:
    """Call GWL serializer and render generator using existing pipeline modules."""
    if param_file is None:
        print("[STEP] Warning: PrintParameters.txt not found — skipping GWL & renders.")
        return

    # ── GWL ──────────────────────────────────────────────────────────────────
    gwl_params = gwl_serializer.load_gwl_parameters(param_file)
    gwl_dir    = output_dir / "GWL"
    gwl_files  = gwl_serializer.generate_gwl_files(output_json, gwl_params, gwl_dir)

    master_gwl = gwl_dir / f"{output_json['job_name']}_master.gwl"
    gwl_serializer.generate_master_gwl(gwl_files, gwl_params, master_gwl)
    print(f"[STEP] GWL written → {gwl_dir.name}/ ({len(gwl_files)} layer files)")

    # ── Renders ───────────────────────────────────────────────────────────────
    render_dir = output_dir / "Renders"
    render_generator_v2.generate_object_aware_renders(design_json, render_dir, param_file)
    print(f"[STEP] Renders written → {render_dir.name}/")


# ======================================================
# TOP-LEVEL ORCHESTRATOR
# ======================================================

def run_step_pipeline(
    step_path: Path,
    job_name: Optional[str] = None,
    hatch_override: Optional[float] = None,
    slice_override: Optional[float] = None,
    contours_override: Optional[int] = None,
) -> Path:
    """
    Full STEP → output.json + GWL + renders pipeline.

    Args:
        step_path:         Path to the .step / .stp file.
        job_name:          Override for job name (defaults to file stem).
        hatch_override:    Hatch spacing in µm (overrides PrintParameters.txt).
        slice_override:    Slice spacing in µm (overrides PrintParameters.txt).
        contours_override: Contour count (overrides PrintParameters.txt).

    Returns:
        Path to the iter_000/ output directory.
    """
    step_path = step_path.resolve()
    if not step_path.exists():
        raise FileNotFoundError(f"STEP file not found: {step_path}")

    job_name = job_name or step_path.stem
    # Sanitise job name for filesystem
    job_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in job_name)

    print("=" * 70)
    print("STEP PIPELINE  —  exact BREP slicing")
    print("=" * 70)
    print(f"[STEP] file     : {step_path.name}")
    print(f"[STEP] job name : {job_name}")

    # ── Find parameters ───────────────────────────────────────────────────────
    param_file = _find_param_file(_V2_DIR)
    params     = _load_params(param_file)

    # Apply CLI overrides
    if hatch_override is not None:
        params["hatch_spacing_um"] = hatch_override
    if slice_override is not None:
        params["slice_spacing_um"] = slice_override
    if contours_override is not None:
        params["solid_contour_count"] = int(contours_override)

    print(f"[STEP] hatch    : {params['hatch_spacing_um']} µm")
    print(f"[STEP] slice    : {params['slice_spacing_um']} µm")
    print(f"[STEP] contours : {params['solid_contour_count']}")
    if param_file:
        print(f"[STEP] params   : {param_file.name}")
    else:
        print("[STEP] params   : defaults (PrintParameters.txt not found)")

    # ── Load STEP ─────────────────────────────────────────────────────────────
    print(f"[STEP] loading STEP file…")
    shape  = load_step(step_path)
    bodies, mode = extract_objects(shape)
    print(f"[STEP] extracted {len(bodies)} body(ies) (mode: {mode})")

    # ── Output directory ──────────────────────────────────────────────────────
    output_dir = _V2_DIR / "Outputs" / job_name / "iter_000"
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"[STEP] output   : {output_dir}")

    # ── Slice → output.json ───────────────────────────────────────────────────
    output_json = build_output_json(bodies, job_name, params)

    out_path = output_dir / "output.json"
    with out_path.open("w") as fh:
        json.dump(output_json, fh, indent=2)
    print(f"[STEP] saved    : output.json "
          f"({output_json['metadata']['num_layers']} layers)")

    # ── Synthetic design.json ─────────────────────────────────────────────────
    design_json = build_design_json(bodies, job_name)

    design_path = output_dir / "design.json"
    with design_path.open("w") as fh:
        json.dump(design_json, fh, indent=2)
    print(f"[STEP] saved    : design.json ({len(bodies)} bodies)")

    # ── GWL + renders ─────────────────────────────────────────────────────────
    if output_json["layers"]:
        _run_downstream(output_dir, output_json, design_json, param_file)
    else:
        print("[STEP] Warning: no layers generated — skipping GWL & renders.")

    print("=" * 70)
    print(f"[STEP] DONE → {output_dir}")
    print("=" * 70)
    return output_dir


# ======================================================
# CLI
# ======================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Slice a STEP file into Nanoscribe GWL toolpaths using exact BREP geometry.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  py src/step_pipeline.py model.step
  py src/step_pipeline.py model.step --job-name pillar_array
  py src/step_pipeline.py model.step --hatch 0.3 --slice 0.5 --contours 3
        """,
    )
    parser.add_argument("step_file", type=Path, help="Path to .step / .stp file")
    parser.add_argument("--job-name", type=str, default=None,
                        help="Override job name (default: STEP file stem)")
    parser.add_argument("--hatch", type=float, default=None,
                        help="Hatch spacing in µm (overrides PrintParameters.txt)")
    parser.add_argument("--slice", type=float, default=None,
                        help="Slice spacing in µm (overrides PrintParameters.txt)")
    parser.add_argument("--contours", type=int, default=None,
                        help="Number of contour passes (overrides PrintParameters.txt)")

    args = parser.parse_args()

    try:
        run_step_pipeline(
            step_path         = args.step_file,
            job_name          = args.job_name,
            hatch_override    = args.hatch,
            slice_override    = args.slice,
            contours_override = args.contours,
        )
    except FileNotFoundError as exc:
        print(f"[STEP] ERROR: {exc}")
        sys.exit(1)
    except Exception as exc:
        print(f"[STEP] ERROR: {exc}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
